require: rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'spec/dummy/**/*'
    - /*.gemspec

Layout/SpaceInLambdaLiteral:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Enabled: true
  Exclude:
    - ./Rakefile

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/FilePath:
  Enabled: false
  IgnoreMethods: true
  SpecSuffixOnly: true

RSpec/AnyInstance:
  Enabled: false
