version: 2.1
orbs:
  ruby: circleci/ruby@1.0.4
  codecov: codecov/codecov@3.2.2
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rake
      - codecov/upload
workflows:
  version: 2
  deploy:
    jobs:
      - test
